name: Code Validation

on:
  push:  # Runs on every commit (push)
    branches:
      - main
      - dev  # Add other branches if needed

  pull_request:  # Runs on every PR
    branches:
      - main
      - dev

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout Code
        uses: actions/checkout@v3

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install frappe-code
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/SSAKTHIVELMURUGAN/Code-Reviewer.git

      - name: ⚙️ Install Dependencies with frappe-code install
        run: frappe-code install

      - name: 🔍 Validate Changed Files (For PRs)
        if: github.event_name == 'pull_request'
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "✅ No files changed, skipping validation."
            exit 0
          fi
          
          PASSED=true
          for file in $CHANGED_FILES; do
            echo "🔍 Validating: $file"
            if frappe-code validate-file "$file"; then
              echo "✅ $file - PASSED"
            else
              echo "❌ $file - FAILED"
              PASSED=false
            fi
          done
          
          if [ "$PASSED" = false ]; then
            echo "❌ Validation Failed!"
            exit 1
          else
            echo "✅ All Files Passed!"
          fi

      - name: ✅ Validate Entire Project (For All Commits & PRs)
        run: |
          echo "🔍 Running full project validation..."
          if frappe-code validate; then
            echo "✅ Project Validation PASSED"
          else
            echo "❌ Project Validation FAILED failed"
            exit 1
          fi
